Type fixes, closes #155
editor-js/table pull request #162
Opened 2024-10-01 06:55 UTC by Sozialarchiv

2024-10-01 08:26 UTC, neSpecc requested changes
Please, attach an issue correctly and write a nice description

2024-10-02 11:20 UTC, neSpecc commented on src/toolbox.js
> +   * @param {any} config.api - Editor.js api
could you import types form editor js package?

2024-10-02 11:42 UTC, Sozialarchiv commented on src/toolbox.js
> +   * @param {any} config.api - Editor.js api
The jsdoc is just a workaround. If you really want to good types the best solution is to migrate to ts.

2024-10-05 12:23 UTC, neSpecc commented on src/toolbox.js
> +   * @param {any} config.api - Editor.js api
I mean something like this

```js
/**
 * @typedef {import('./types').MyType} MyType
 */
```

2024-10-09 15:10 UTC, neSpecc commented on src/toolbox.js
> +   * @param {any} config.api - Editor.js api
Hey, @Sozialarchiv would you be able to try it?

2024-10-11 17:03 UTC, Sozialarchiv commented on src/toolbox.js
> +   * @param {any} config.api - Editor.js api
I will take a look at it.

2024-11-11 19:31 UTC, neSpecc approved these changes

2024-11-11 19:32 UTC, merged