New beautiful table
editor-js/table pull request #67
Opened 2021-05-07 17:29 UTC by GeekaN2

2021-06-18 17:21 UTC, neSpecc requested changes

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +      if (row) {
comments needed

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +    this.numberOfColumns--;
maybe its better to create a getter that will always return an actual value?

```
get columnsCount(){
  return ... // calculate from DOM
}
```

in this case you won't need to increment/decrement a property

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +    this.numberOfColumns--;
or it can occur performance issue? Will it called in a loop?

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
>    get htmlElement() {
name is not clear. What an element?

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
>    /**
update doc

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +   * Create wrapper with an additional interface
what does it mean?

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +      const newCell = create('div', [ CSS.cell ], { contenteditable: !this.readOnly });
its the second place where you're creating a cell. Can you do it in a single place?

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +    }, true);
passive: true

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +      document.addEventListener('click', this.clickOutsideWrapperListener);
you're adding a new click event on every mouse move? really?

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +    this.element.querySelector(`.${CSS.addColumn}`).addEventListener('click', (event) => {
don't use query selector in a methods. Save this button to the variable

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +      this.hideEverything();
name is not clear

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +    this.element.querySelector(`.${CSS.addRow}`).addEventListener('click', (event) => {
don't add such a many event listeners. Use delegation. Add a single listener to the document and detect clicked element in there.


```js
const addRowClicked = event.target.closest(`.{CSS.addRow}`);

if (addRowClicked){
  this.addRow()
}
```

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +      this.addColumn(this.hoveredColumn + 1);
it is not clear , where this.hoveredColumn is updated?

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +    // Add a column to the left
use block comments

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +        this.showDeleteColumnConfirmation = true;
move it to the `this.toolbox.setDeleteColumnConfirmation();`

it is related to the Toolbox class.

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +      this.unselectColumn();
move handlers to the separate methods. describe their workflow

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +      if (event.key == 'Enter' && event.shiftKey) {
add comment

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +        if (this.focusedCell.row != this.numberOfRows) {
move to the method

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +      return event.key != 'Enter';
add a comment

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +      if (event.key == 'Tab') {
add a comment

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +  useHeadings(withHeadings) {
name is not clear

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +    this.lastSelectedRow = index;
you have an `if` statement, so move this setter there

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +      const { row, column } = this.hoveredCell(event);
this method has many calculations, so please optimise it. Add a throttling, make listener a passive and so on.

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +    this.table.addEventListener('mousemove', (event) => {
be aware of using such events, because they're fired many times in a row. Optimise them.

2021-06-18 17:21 UTC, neSpecc commented on src/table.js
> +  hoveredCell(event) {
please optimise this method

2021-06-18 17:21 UTC, neSpecc commented on src/toolbox.js
> +    addRowAboveText.textContent = 'Add row above';
use i18n

2021-06-18 17:21 UTC, neSpecc commented on src/toolbox.js
> +   * Change column toolbox position
what does it mean?

2021-06-18 17:21 UTC, neSpecc commented on src/toolbox.js
> +   * Change row toolbox position
what does it mean "row position"?

2021-06-18 17:25 UTC, neSpecc requested changes
where is the `destroy()` method?

2021-06-26 12:18 UTC, neSpecc requested changes

2021-06-26 12:18 UTC, neSpecc commented on src/table.js
> +    this.toolbox.toolboxColumn.addEventListener('click', (event) => {
move handler

2021-06-26 12:18 UTC, neSpecc commented on src/table.js
> +      if (addColumnLeftClicked) {
`if else` or `return`

2021-06-26 12:18 UTC, neSpecc commented on src/table.js
> +
can we move these lines to some util? They are similar with previous

2021-06-26 12:18 UTC, neSpecc commented on src/table.js
> +      if (event.key == 'Enter') {
duplicated statement

2021-06-26 12:18 UTC, neSpecc commented on src/table.js
> +    this.table.addEventListener('keydown', (event) => {
why `keydown` and `keypress` are different handlers?

2021-06-26 12:18 UTC, neSpecc commented on src/table.js
> +      const row = cell.parentElement;
use method `getRowByCell()`

2021-06-26 12:18 UTC, neSpecc commented on src/table.js
> +    if (y >= 0 && !hoveredRow) {
do not repeat yourself

2021-06-26 12:18 UTC, neSpecc commented on src/table.js
> +        const { fromRightBorder, fromLeftBorder } = getRelativeCoordsOfTwoElems(this.table, cell);
1. describe why you need this? 
2. Can you calculate and cache values before iteration?

2021-06-26 12:18 UTC, neSpecc commented on src/toolbox.js
> +  toolboxAddRowBelow: 'tc-toolbox-add-row-below',
do not copy indentifiers

2021-06-26 12:18 UTC, neSpecc commented on src/toolbox.js
> +    this.toolboxRow = this.createToolboxRow();
separate to different classes

2021-06-26 12:18 UTC, neSpecc commented on src/toolbox.js
> +    let addRowAbove = create('div', [CSS.toolboxAddRowAbove, CSS.toolboxOption]);
use cycle for rendering

2021-06-26 12:18 UTC, neSpecc commented on src/toolbox.js
> +    this.toolboxColumnMenu.querySelector(`.${CSS.toolboxDeleteColumn}`).classList.add(CSS.displayNone);
do not use DOM search

2021-06-26 12:18 UTC, neSpecc commented on src/toolbox.js
> +      this.toolboxColumn.style.cssText = 'opacity: 1; ' + `left: calc((100% - 35px) / (${numberOfColumns} * 2) * (1 + (${column} - 1) * 2))`;
comment required

2021-07-22 15:34 UTC, neSpecc approved these changes

2021-07-22 15:35 UTC, talyguryn approved these changes

2021-07-22 16:18 UTC, merged